---
cisco:
  connection_options:
    netmiko:
      extras:
        fast_cli: false
        # If you need enable (privileged) mode on IOS/IOS-XE/IOS-XR:
        # secret: "YOUR_ENABLE_PASSWORD"
        # Optional session logs (ensure the directory exists or remove this):
        session_log: "logs/{host}-netmiko.log"

juniper:
  connection_options:
    netmiko:
      extras:
        fast_cli: true